sudo: required
language: node_js
node_js:
  - "node"
services:
  - docker
language: bash
script:
- docker run --privileged linuxkit/binfmt:v0.7
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
# build and push images 
- ./build_n_push.sh
- docker images
