#!/bin/bash
export DOCKER_CLI_EXPERIMENTAL=enabled
#docker buildx create --use --name multiarchimage-buildertest
docker buildx create --name multiarchimage-buildertest
docker buildx use multiarchimage-buildertest
docker buildx inspect --bootstrap

docker buildx build --push -t bagalvitthal/mypm2:latest --platform linux/amd64,linux/s390x .

