#!/usr/bin/env bash
set -eu

echo " Install qemu + binfmt support"

curl -L https://github.com/multiarch/qemu-user-static/releases/download/v4.0.0-2/qemu-s390x-static.tar.gz | tar zxvf - -C /usr/local/bin
cp /usr/local/bin/qemu-s390x-static qemu-s390x-static

ls -la
