#!/bin/bash

# Register qemu-*-static for all supported processors except the 
# current one, but also remove all registered binfmt_misc before
cat /etc/os-release
docker --version
#apt-get update
#apt install -y qemu qemu-user-static qemu-user binfmt-support crossbuild-essential* 
docker run --privileged linuxkit/binfmt:v0.7
#docker run --rm --privileged multiarch/qemu-user-static:register --reset
#docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
