#!/bin/bash

# Register qemu-*-static for all supported processors except the 
# current one, but also remove all registered binfmt_misc before
cat /etc/os-release
docker --version

#apt-get update
docker run --rm --privileged docker/binfmt:66f9012c56a8316f9244ffd7622d7c21c1f6f28d
#docker run --rm --privileged multiarch/qemu-user-static:4.2.0-7 --reset -p yes
docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

